// <auto-generated />
using MapaWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;

#nullable disable

namespace MapaWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
<<<<<<<< HEAD:MapaWeb/Migrations/20251031123718_MigracionInicial.Designer.cs
========
<<<<<<<< HEAD:MapaWeb/Migrations/20251031112912_MapaWeb.Designer.cs
    [Migration("20251031112912_MapaWeb")]
    partial class MapaWeb
========
>>>>>>>> bf58317f9111719693eb87794629ca9af9b32940:MapaWeb/Migrations/20251031112912_MapaWeb.Designer.cs
    [Migration("20251031123718_MigracionInicial")]
    partial class MigracionInicial
>>>>>>>> 82f565b (sistema de poligonos funcando de 10):MapaWeb/Migrations/20251031123718_MigracionInicial.Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MapaWeb.Models.Marcador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Point>("Ubicacion")
                        .IsRequired()
                        .HasColumnType("geography");

                    b.HasKey("Id");

                    b.ToTable("Marcadores");
                });

            modelBuilder.Entity("Poligono", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Polygon>("Geometria")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Poligonos");
                });
#pragma warning restore 612, 618
        }
    }
}
